# Generated by Django 3.1.6 on 2021-02-11 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='time_taken',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
