# Generated by Django 3.1.6 on 2021-02-11 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_list_time_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='time_taken',
        ),
    ]
