# Generated by Django 3.1.6 on 2021-02-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0004_list_expected_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='frequency',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
