# Generated by Django 3.1.6 on 2021-02-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0006_calendar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={},
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='notes',
        ),
        migrations.AddField(
            model_name='calendar',
            name='title',
            field=models.CharField(default='This is the default task', max_length=200),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='end_time',
            field=models.IntegerField(default=29),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='start_time',
            field=models.IntegerField(default=28),
        ),
    ]
