# Generated by Django 3.1.6 on 2021-02-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0007_auto_20210212_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='title',
            new_name='task',
        ),
        migrations.AlterField(
            model_name='calendar',
            name='day',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='end_time',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='start_time',
            field=models.IntegerField(default=14),
        ),
    ]
