# Generated by Django 3.1.6 on 2021-02-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0008_auto_20210212_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='This is the default task', max_length=200)),
                ('day', models.IntegerField(default=7)),
                ('start_time', models.IntegerField(default=14)),
                ('end_time', models.IntegerField(default=15)),
            ],
        ),
    ]
